// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/chat/chat.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatDeliveryService_DeliverMessage_FullMethodName       = "/chat.ChatDeliveryService/DeliverMessage"
	ChatDeliveryService_DeliverSystemMessage_FullMethodName = "/chat.ChatDeliveryService/DeliverSystemMessage"
)

// ChatDeliveryServiceClient is the client API for ChatDeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatDeliveryServiceClient interface {
	DeliverMessage(ctx context.Context, in *DeliverMessageRequest, opts ...grpc.CallOption) (*DeliverMessageResponse, error)
	DeliverSystemMessage(ctx context.Context, in *DeliverSystemMessageRequest, opts ...grpc.CallOption) (*DeliverSystemMessageResponse, error)
}

type chatDeliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatDeliveryServiceClient(cc grpc.ClientConnInterface) ChatDeliveryServiceClient {
	return &chatDeliveryServiceClient{cc}
}

func (c *chatDeliveryServiceClient) DeliverMessage(ctx context.Context, in *DeliverMessageRequest, opts ...grpc.CallOption) (*DeliverMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverMessageResponse)
	err := c.cc.Invoke(ctx, ChatDeliveryService_DeliverMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatDeliveryServiceClient) DeliverSystemMessage(ctx context.Context, in *DeliverSystemMessageRequest, opts ...grpc.CallOption) (*DeliverSystemMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverSystemMessageResponse)
	err := c.cc.Invoke(ctx, ChatDeliveryService_DeliverSystemMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatDeliveryServiceServer is the server API for ChatDeliveryService service.
// All implementations must embed UnimplementedChatDeliveryServiceServer
// for forward compatibility.
type ChatDeliveryServiceServer interface {
	DeliverMessage(context.Context, *DeliverMessageRequest) (*DeliverMessageResponse, error)
	DeliverSystemMessage(context.Context, *DeliverSystemMessageRequest) (*DeliverSystemMessageResponse, error)
	mustEmbedUnimplementedChatDeliveryServiceServer()
}

// UnimplementedChatDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatDeliveryServiceServer struct{}

func (UnimplementedChatDeliveryServiceServer) DeliverMessage(context.Context, *DeliverMessageRequest) (*DeliverMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverMessage not implemented")
}
func (UnimplementedChatDeliveryServiceServer) DeliverSystemMessage(context.Context, *DeliverSystemMessageRequest) (*DeliverSystemMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverSystemMessage not implemented")
}
func (UnimplementedChatDeliveryServiceServer) mustEmbedUnimplementedChatDeliveryServiceServer() {}
func (UnimplementedChatDeliveryServiceServer) testEmbeddedByValue()                             {}

// UnsafeChatDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatDeliveryServiceServer will
// result in compilation errors.
type UnsafeChatDeliveryServiceServer interface {
	mustEmbedUnimplementedChatDeliveryServiceServer()
}

func RegisterChatDeliveryServiceServer(s grpc.ServiceRegistrar, srv ChatDeliveryServiceServer) {
	// If the following call panics, it indicates UnimplementedChatDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatDeliveryService_ServiceDesc, srv)
}

func _ChatDeliveryService_DeliverMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatDeliveryServiceServer).DeliverMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatDeliveryService_DeliverMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatDeliveryServiceServer).DeliverMessage(ctx, req.(*DeliverMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatDeliveryService_DeliverSystemMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverSystemMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatDeliveryServiceServer).DeliverSystemMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatDeliveryService_DeliverSystemMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatDeliveryServiceServer).DeliverSystemMessage(ctx, req.(*DeliverSystemMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatDeliveryService_ServiceDesc is the grpc.ServiceDesc for ChatDeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatDeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatDeliveryService",
	HandlerType: (*ChatDeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliverMessage",
			Handler:    _ChatDeliveryService_DeliverMessage_Handler,
		},
		{
			MethodName: "DeliverSystemMessage",
			Handler:    _ChatDeliveryService_DeliverSystemMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/chat/chat.proto",
}
