// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/id/id.proto

package id

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IDType int32

const (
	IDType_ID_TYPE_SNOWFLAKE IDType = 0
	IDType_ID_TYPE_UUID      IDType = 1
	IDType_ID_TYPE_ULID      IDType = 2
	IDType_ID_TYPE_KSUID     IDType = 3
	IDType_ID_TYPE_NANOID    IDType = 4
	IDType_ID_TYPE_CUID2     IDType = 5
)

// Enum value maps for IDType.
var (
	IDType_name = map[int32]string{
		0: "ID_TYPE_SNOWFLAKE",
		1: "ID_TYPE_UUID",
		2: "ID_TYPE_ULID",
		3: "ID_TYPE_KSUID",
		4: "ID_TYPE_NANOID",
		5: "ID_TYPE_CUID2",
	}
	IDType_value = map[string]int32{
		"ID_TYPE_SNOWFLAKE": 0,
		"ID_TYPE_UUID":      1,
		"ID_TYPE_ULID":      2,
		"ID_TYPE_KSUID":     3,
		"ID_TYPE_NANOID":    4,
		"ID_TYPE_CUID2":     5,
	}
)

func (x IDType) Enum() *IDType {
	p := new(IDType)
	*p = x
	return p
}

func (x IDType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IDType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_id_id_proto_enumTypes[0].Descriptor()
}

func (IDType) Type() protoreflect.EnumType {
	return &file_proto_id_id_proto_enumTypes[0]
}

func (x IDType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IDType.Descriptor instead.
func (IDType) EnumDescriptor() ([]byte, []int) {
	return file_proto_id_id_proto_rawDescGZIP(), []int{0}
}

type GenerateIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          IDType                 `protobuf:"varint,1,opt,name=type,proto3,enum=id.IDType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIDRequest) Reset() {
	*x = GenerateIDRequest{}
	mi := &file_proto_id_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIDRequest) ProtoMessage() {}

func (x *GenerateIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_id_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIDRequest.ProtoReflect.Descriptor instead.
func (*GenerateIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_id_id_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateIDRequest) GetType() IDType {
	if x != nil {
		return x.Type
	}
	return IDType_ID_TYPE_SNOWFLAKE
}

type GenerateIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIDResponse) Reset() {
	*x = GenerateIDResponse{}
	mi := &file_proto_id_id_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIDResponse) ProtoMessage() {}

func (x *GenerateIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_id_id_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIDResponse.ProtoReflect.Descriptor instead.
func (*GenerateIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_id_id_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GenerateBatchIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          IDType                 `protobuf:"varint,1,opt,name=type,proto3,enum=id.IDType" json:"type,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // 上限 1000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateBatchIDsRequest) Reset() {
	*x = GenerateBatchIDsRequest{}
	mi := &file_proto_id_id_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateBatchIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateBatchIDsRequest) ProtoMessage() {}

func (x *GenerateBatchIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_id_id_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateBatchIDsRequest.ProtoReflect.Descriptor instead.
func (*GenerateBatchIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_id_id_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateBatchIDsRequest) GetType() IDType {
	if x != nil {
		return x.Type
	}
	return IDType_ID_TYPE_SNOWFLAKE
}

func (x *GenerateBatchIDsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GenerateBatchIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateBatchIDsResponse) Reset() {
	*x = GenerateBatchIDsResponse{}
	mi := &file_proto_id_id_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateBatchIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateBatchIDsResponse) ProtoMessage() {}

func (x *GenerateBatchIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_id_id_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateBatchIDsResponse.ProtoReflect.Descriptor instead.
func (*GenerateBatchIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_id_id_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateBatchIDsResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ValidateIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          IDType                 `protobuf:"varint,1,opt,name=type,proto3,enum=id.IDType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateIDRequest) Reset() {
	*x = ValidateIDRequest{}
	mi := &file_proto_id_id_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateIDRequest) ProtoMessage() {}

func (x *ValidateIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_id_id_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateIDRequest.ProtoReflect.Descriptor instead.
func (*ValidateIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_id_id_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateIDRequest) GetType() IDType {
	if x != nil {
		return x.Type
	}
	return IDType_ID_TYPE_SNOWFLAKE
}

func (x *ValidateIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ValidateIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // 失敗原因（valid=true 時為空）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateIDResponse) Reset() {
	*x = ValidateIDResponse{}
	mi := &file_proto_id_id_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateIDResponse) ProtoMessage() {}

func (x *ValidateIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_id_id_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateIDResponse.ProtoReflect.Descriptor instead.
func (*ValidateIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_id_id_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateIDResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateIDResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ParseIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          IDType                 `protobuf:"varint,1,opt,name=type,proto3,enum=id.IDType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseIDRequest) Reset() {
	*x = ParseIDRequest{}
	mi := &file_proto_id_id_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseIDRequest) ProtoMessage() {}

func (x *ParseIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_id_id_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseIDRequest.ProtoReflect.Descriptor instead.
func (*ParseIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_id_id_proto_rawDescGZIP(), []int{6}
}

func (x *ParseIDRequest) GetType() IDType {
	if x != nil {
		return x.Type
	}
	return IDType_ID_TYPE_SNOWFLAKE
}

func (x *ParseIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ParseIDResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Valid        bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Snowflake fields
	TimestampMs int64 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // Unix ms（absolute，已加回 epoch）
	MachineId   int64 `protobuf:"varint,4,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Sequence    int64 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// UUID fields
	UuidVersion int32  `protobuf:"varint,6,opt,name=uuid_version,json=uuidVersion,proto3" json:"uuid_version,omitempty"` // 4 for v4
	UuidVariant string `protobuf:"bytes,7,opt,name=uuid_variant,json=uuidVariant,proto3" json:"uuid_variant,omitempty"`  // "RFC4122"
	// ULID/KSUID fields
	RandomPayload string `protobuf:"bytes,8,opt,name=random_payload,json=randomPayload,proto3" json:"random_payload,omitempty"` // hex-encoded random bytes
	// NanoID/CUID2 fields
	IdLength      int32  `protobuf:"varint,9,opt,name=id_length,json=idLength,proto3" json:"id_length,omitempty"` // ID string length
	Alphabet      string `protobuf:"bytes,10,opt,name=alphabet,proto3" json:"alphabet,omitempty"`                 // NanoID: character set used
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseIDResponse) Reset() {
	*x = ParseIDResponse{}
	mi := &file_proto_id_id_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseIDResponse) ProtoMessage() {}

func (x *ParseIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_id_id_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseIDResponse.ProtoReflect.Descriptor instead.
func (*ParseIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_id_id_proto_rawDescGZIP(), []int{7}
}

func (x *ParseIDResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ParseIDResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ParseIDResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ParseIDResponse) GetMachineId() int64 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

func (x *ParseIDResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ParseIDResponse) GetUuidVersion() int32 {
	if x != nil {
		return x.UuidVersion
	}
	return 0
}

func (x *ParseIDResponse) GetUuidVariant() string {
	if x != nil {
		return x.UuidVariant
	}
	return ""
}

func (x *ParseIDResponse) GetRandomPayload() string {
	if x != nil {
		return x.RandomPayload
	}
	return ""
}

func (x *ParseIDResponse) GetIdLength() int32 {
	if x != nil {
		return x.IdLength
	}
	return 0
}

func (x *ParseIDResponse) GetAlphabet() string {
	if x != nil {
		return x.Alphabet
	}
	return ""
}

var File_proto_id_id_proto protoreflect.FileDescriptor

const file_proto_id_id_proto_rawDesc = "" +
	"\n" +
	"\x11proto/id/id.proto\x12\x02id\"3\n" +
	"\x11GenerateIDRequest\x12\x1e\n" +
	"\x04type\x18\x01 \x01(\x0e2\n" +
	".id.IDTypeR\x04type\"$\n" +
	"\x12GenerateIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x17GenerateBatchIDsRequest\x12\x1e\n" +
	"\x04type\x18\x01 \x01(\x0e2\n" +
	".id.IDTypeR\x04type\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\",\n" +
	"\x18GenerateBatchIDsResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"C\n" +
	"\x11ValidateIDRequest\x12\x1e\n" +
	"\x04type\x18\x01 \x01(\x0e2\n" +
	".id.IDTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"B\n" +
	"\x12ValidateIDResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"@\n" +
	"\x0eParseIDRequest\x12\x1e\n" +
	"\x04type\x18\x01 \x01(\x0e2\n" +
	".id.IDTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xd0\x02\n" +
	"\x0fParseIDResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x04 \x01(\x03R\tmachineId\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x03R\bsequence\x12!\n" +
	"\fuuid_version\x18\x06 \x01(\x05R\vuuidVersion\x12!\n" +
	"\fuuid_variant\x18\a \x01(\tR\vuuidVariant\x12%\n" +
	"\x0erandom_payload\x18\b \x01(\tR\rrandomPayload\x12\x1b\n" +
	"\tid_length\x18\t \x01(\x05R\bidLength\x12\x1a\n" +
	"\balphabet\x18\n" +
	" \x01(\tR\balphabet*}\n" +
	"\x06IDType\x12\x15\n" +
	"\x11ID_TYPE_SNOWFLAKE\x10\x00\x12\x10\n" +
	"\fID_TYPE_UUID\x10\x01\x12\x10\n" +
	"\fID_TYPE_ULID\x10\x02\x12\x11\n" +
	"\rID_TYPE_KSUID\x10\x03\x12\x12\n" +
	"\x0eID_TYPE_NANOID\x10\x04\x12\x11\n" +
	"\rID_TYPE_CUID2\x10\x052\x88\x02\n" +
	"\tIDService\x12;\n" +
	"\n" +
	"GenerateID\x12\x15.id.GenerateIDRequest\x1a\x16.id.GenerateIDResponse\x12M\n" +
	"\x10GenerateBatchIDs\x12\x1b.id.GenerateBatchIDsRequest\x1a\x1c.id.GenerateBatchIDsResponse\x12;\n" +
	"\n" +
	"ValidateID\x12\x15.id.ValidateIDRequest\x1a\x16.id.ValidateIDResponse\x122\n" +
	"\aParseID\x12\x12.id.ParseIDRequest\x1a\x13.id.ParseIDResponseB,Z*github.com/weiawesome/wes-io-live/proto/idb\x06proto3"

var (
	file_proto_id_id_proto_rawDescOnce sync.Once
	file_proto_id_id_proto_rawDescData []byte
)

func file_proto_id_id_proto_rawDescGZIP() []byte {
	file_proto_id_id_proto_rawDescOnce.Do(func() {
		file_proto_id_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_id_id_proto_rawDesc), len(file_proto_id_id_proto_rawDesc)))
	})
	return file_proto_id_id_proto_rawDescData
}

var file_proto_id_id_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_id_id_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_id_id_proto_goTypes = []any{
	(IDType)(0),                      // 0: id.IDType
	(*GenerateIDRequest)(nil),        // 1: id.GenerateIDRequest
	(*GenerateIDResponse)(nil),       // 2: id.GenerateIDResponse
	(*GenerateBatchIDsRequest)(nil),  // 3: id.GenerateBatchIDsRequest
	(*GenerateBatchIDsResponse)(nil), // 4: id.GenerateBatchIDsResponse
	(*ValidateIDRequest)(nil),        // 5: id.ValidateIDRequest
	(*ValidateIDResponse)(nil),       // 6: id.ValidateIDResponse
	(*ParseIDRequest)(nil),           // 7: id.ParseIDRequest
	(*ParseIDResponse)(nil),          // 8: id.ParseIDResponse
}
var file_proto_id_id_proto_depIdxs = []int32{
	0, // 0: id.GenerateIDRequest.type:type_name -> id.IDType
	0, // 1: id.GenerateBatchIDsRequest.type:type_name -> id.IDType
	0, // 2: id.ValidateIDRequest.type:type_name -> id.IDType
	0, // 3: id.ParseIDRequest.type:type_name -> id.IDType
	1, // 4: id.IDService.GenerateID:input_type -> id.GenerateIDRequest
	3, // 5: id.IDService.GenerateBatchIDs:input_type -> id.GenerateBatchIDsRequest
	5, // 6: id.IDService.ValidateID:input_type -> id.ValidateIDRequest
	7, // 7: id.IDService.ParseID:input_type -> id.ParseIDRequest
	2, // 8: id.IDService.GenerateID:output_type -> id.GenerateIDResponse
	4, // 9: id.IDService.GenerateBatchIDs:output_type -> id.GenerateBatchIDsResponse
	6, // 10: id.IDService.ValidateID:output_type -> id.ValidateIDResponse
	8, // 11: id.IDService.ParseID:output_type -> id.ParseIDResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_id_id_proto_init() }
func file_proto_id_id_proto_init() {
	if File_proto_id_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_id_id_proto_rawDesc), len(file_proto_id_id_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_id_id_proto_goTypes,
		DependencyIndexes: file_proto_id_id_proto_depIdxs,
		EnumInfos:         file_proto_id_id_proto_enumTypes,
		MessageInfos:      file_proto_id_id_proto_msgTypes,
	}.Build()
	File_proto_id_id_proto = out.File
	file_proto_id_id_proto_goTypes = nil
	file_proto_id_id_proto_depIdxs = nil
}
