// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/id/id.proto

package id

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IDService_GenerateID_FullMethodName       = "/id.IDService/GenerateID"
	IDService_GenerateBatchIDs_FullMethodName = "/id.IDService/GenerateBatchIDs"
	IDService_ValidateID_FullMethodName       = "/id.IDService/ValidateID"
	IDService_ParseID_FullMethodName          = "/id.IDService/ParseID"
)

// IDServiceClient is the client API for IDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IDServiceClient interface {
	GenerateID(ctx context.Context, in *GenerateIDRequest, opts ...grpc.CallOption) (*GenerateIDResponse, error)
	GenerateBatchIDs(ctx context.Context, in *GenerateBatchIDsRequest, opts ...grpc.CallOption) (*GenerateBatchIDsResponse, error)
	ValidateID(ctx context.Context, in *ValidateIDRequest, opts ...grpc.CallOption) (*ValidateIDResponse, error)
	ParseID(ctx context.Context, in *ParseIDRequest, opts ...grpc.CallOption) (*ParseIDResponse, error)
}

type iDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIDServiceClient(cc grpc.ClientConnInterface) IDServiceClient {
	return &iDServiceClient{cc}
}

func (c *iDServiceClient) GenerateID(ctx context.Context, in *GenerateIDRequest, opts ...grpc.CallOption) (*GenerateIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateIDResponse)
	err := c.cc.Invoke(ctx, IDService_GenerateID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iDServiceClient) GenerateBatchIDs(ctx context.Context, in *GenerateBatchIDsRequest, opts ...grpc.CallOption) (*GenerateBatchIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateBatchIDsResponse)
	err := c.cc.Invoke(ctx, IDService_GenerateBatchIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iDServiceClient) ValidateID(ctx context.Context, in *ValidateIDRequest, opts ...grpc.CallOption) (*ValidateIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateIDResponse)
	err := c.cc.Invoke(ctx, IDService_ValidateID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iDServiceClient) ParseID(ctx context.Context, in *ParseIDRequest, opts ...grpc.CallOption) (*ParseIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseIDResponse)
	err := c.cc.Invoke(ctx, IDService_ParseID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IDServiceServer is the server API for IDService service.
// All implementations must embed UnimplementedIDServiceServer
// for forward compatibility.
type IDServiceServer interface {
	GenerateID(context.Context, *GenerateIDRequest) (*GenerateIDResponse, error)
	GenerateBatchIDs(context.Context, *GenerateBatchIDsRequest) (*GenerateBatchIDsResponse, error)
	ValidateID(context.Context, *ValidateIDRequest) (*ValidateIDResponse, error)
	ParseID(context.Context, *ParseIDRequest) (*ParseIDResponse, error)
	mustEmbedUnimplementedIDServiceServer()
}

// UnimplementedIDServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIDServiceServer struct{}

func (UnimplementedIDServiceServer) GenerateID(context.Context, *GenerateIDRequest) (*GenerateIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateID not implemented")
}
func (UnimplementedIDServiceServer) GenerateBatchIDs(context.Context, *GenerateBatchIDsRequest) (*GenerateBatchIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateBatchIDs not implemented")
}
func (UnimplementedIDServiceServer) ValidateID(context.Context, *ValidateIDRequest) (*ValidateIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateID not implemented")
}
func (UnimplementedIDServiceServer) ParseID(context.Context, *ParseIDRequest) (*ParseIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseID not implemented")
}
func (UnimplementedIDServiceServer) mustEmbedUnimplementedIDServiceServer() {}
func (UnimplementedIDServiceServer) testEmbeddedByValue()                   {}

// UnsafeIDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IDServiceServer will
// result in compilation errors.
type UnsafeIDServiceServer interface {
	mustEmbedUnimplementedIDServiceServer()
}

func RegisterIDServiceServer(s grpc.ServiceRegistrar, srv IDServiceServer) {
	// If the following call panics, it indicates UnimplementedIDServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IDService_ServiceDesc, srv)
}

func _IDService_GenerateID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDServiceServer).GenerateID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IDService_GenerateID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDServiceServer).GenerateID(ctx, req.(*GenerateIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IDService_GenerateBatchIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateBatchIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDServiceServer).GenerateBatchIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IDService_GenerateBatchIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDServiceServer).GenerateBatchIDs(ctx, req.(*GenerateBatchIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IDService_ValidateID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDServiceServer).ValidateID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IDService_ValidateID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDServiceServer).ValidateID(ctx, req.(*ValidateIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IDService_ParseID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDServiceServer).ParseID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IDService_ParseID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDServiceServer).ParseID(ctx, req.(*ParseIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IDService_ServiceDesc is the grpc.ServiceDesc for IDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "id.IDService",
	HandlerType: (*IDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateID",
			Handler:    _IDService_GenerateID_Handler,
		},
		{
			MethodName: "GenerateBatchIDs",
			Handler:    _IDService_GenerateBatchIDs_Handler,
		},
		{
			MethodName: "ValidateID",
			Handler:    _IDService_ValidateID_Handler,
		},
		{
			MethodName: "ParseID",
			Handler:    _IDService_ParseID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/id/id.proto",
}
